/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bisq;

import io.reactivex.rxjava3.core.Emitter;
import io.reactivex.rxjava3.core.Observable;
import io.reactivex.rxjava3.functions.Consumer;

import java.util.Random;

public class HelloRx {

    public static void main(String[] args) {

        Consumer<Emitter<Integer>> c = emitter -> {
            emitter.onNext(new Random().nextInt());
            Thread.sleep(1000);
        };
        System.out.println("here");
        Observable.generate(c).subscribe(System.out::println);
        System.out.println("there");
    }
}
