/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bisq;

import org.junit.jupiter.api.Test;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;

import static org.junit.jupiter.api.Assertions.*;

class ServerTest {
    @Test
    void listensOnPort_ReturnsValue_AndExits() throws IOException {
        Server server = new Server();
        new Thread(server).start();

        try (Socket client = new Socket("localhost", 9999);
             BufferedReader in = new BufferedReader(new InputStreamReader(client.getInputStream()))) {
            String ret = in.readLine();
            assertEquals("42", ret);
        }
    }
}