/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bisq;

public class Cli implements Runnable {
    public static void main(String[] args) {
        new Cli().run();
    }

    @Override
    public void run() {
        bisq.Client client = new bisq.Client("localhost", 9999);
        System.out.println("version: " + client.getVersion());
    }
}
