/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bisq.cli;

import bisq.client.BisqNode;

public class BisqCli implements Runnable {
    public static void main(String[] args) {
        new BisqCli().run();
    }

    @Override
    public void run() {
        BisqNode bisqNode = new BisqNode("localhost", 9999);
        System.out.println("version: " + bisqNode.getVersion());
    }
}
