/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bisq;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;

public class Cli implements Runnable {
    public static void main(String[] args) {
        new Cli().run();
    }

    @Override
    public void run() {
        try {
            try (Socket client = new Socket("localhost", 9999);
                 BufferedReader in = new BufferedReader(new InputStreamReader(client.getInputStream()))) {
                String ret = in.readLine();
                System.out.println(ret);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
