/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bisq.app.cli;

import bisq.api.http.client.HttpApiClient;

public class BisqCli {

    public static final int EXIT_SUCCESS = 0;
    public static final int EXIT_FAILURE = 1;

    private Console console = new SystemConsole();

    private final HttpApiClient client;
    private final String command;

    public BisqCli(String... args) {
        if (args.length != 1)
            throw new IllegalArgumentException("usage: bisq-cli <command>");
        this.client = new HttpApiClient("localhost", 9999);
        this.command = args[0];
    }

    public int run() {
        switch (command) {
            case "getversion" -> console.outln(client.getVersion());
            case "getprice" -> console.outln(client.getPrice());
            default -> {
                console.errln("unsupported command: " + command);
                return EXIT_FAILURE;
            }
        }
        return EXIT_SUCCESS;
    }

    void setConsole(Console console) {
        this.console = console;
    }

    public static void main(String[] args) {
        System.exit(new BisqCli(args).run());
    }
}
