/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bisq.app.cli;

import bisq.api.client.ApiClient;
import bisq.api.http.client.HttpApiClient;

public class BisqCli implements Runnable {

    private final ApiClient client;
    private final String command;

    public BisqCli(String[] args) {
        if (args.length != 1)
            throw new IllegalArgumentException("usage: bisq-cli <command>");
        this.client = new HttpApiClient("localhost", 9999);
        this.command = args[0];
    }

    @Override
    public void run() {
        switch (command) {
            case "getversion" -> System.out.println(client.getVersion());
            case "getprice" -> System.out.println(client.getPrice());
            default -> throw new UnsupportedOperationException("unsupported command: " + command);
        }
    }

    public static void main(String[] args) {
        new BisqCli(args).run();
    }
}
