/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bisq;

public class Daemon {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Daemon().getGreeting());
    }
}
