/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bisq;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class DaemonTest {
    @Test
    void appHasAGreeting() {
        Daemon classUnderTest = new Daemon();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
